name: Update README with Username

on:
  schedule:
    - cron: '0 * * * *'  # Runs the workflow every hour (you can adjust this)
  workflow_dispatch:  # Allows you to trigger manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Fetch GitHub Username
        run: echo "USER_NAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Update README
        run: |
          echo "# Hello, $USER_NAME! 👋" > README.md
          echo "Welcome to my GitHub profile! Have a great day, $USER_NAME!" >> README.md

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          git commit -m "Update greeting with username"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
